[package]
name = "multi-bind-rb"
version = "0.1.0"
edition = "2021"

[lib]
name = "multi_bind_rb"
crate-type = ["cdylib"]

[dependencies]
multi-bind = { path = "../" }
tokio = { version = "1.40.0", features = ["full"] }
